name: Go (test-integration)

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y libbtrfs-dev libdevmapper-dev libgpgme-dev pkg-config build-essential libdpkg-dev

      - name: Build
        run: go build -o abrootv2

      - name: Test
        run: go test -v ./tests/...

      - name: Compress
        run: tar -czvf abrootv2.tar.gz abrootv2

      - name: Compress-manpage
        run: tar -czvf abroot-man.tar.gz man/man1/abroot.1

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            abrootv2.tar.gz
            abroot-man.tar.gz

  test:
    name: Integration Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
      options: |
        --privileged
        --device /dev/kvm
        --cap-add=ALL
        --security-opt seccomp=unconfined
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y parted mount kpartx kmod dosfstools libbtrfs-dev libdevmapper-dev libgpgme-dev pkg-config build-essential libdpkg-dev qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virt-manager

      - name: Verify KVM
        run: |
          lsmod | grep kvm
          kvm-ok || echo "KVM is not supported"
          sudo kvm-ok || echo "KVM is not supported"

      - name: Extract Build
        run: |
          tar -xzvf artifacts/abrootv2.tar.gz -C .

      - name: Create Virtual Disks Images
        run: |
          dd if=/dev/zero of=vos-var.img bs=1M count=1024
          dd if=/dev/zero of=vos-a.img bs=1M count=1024
          dd if=/dev/zero of=vos-b.img bs=1M count=1024
          dd if=/dev/zero of=vos-boot.img bs=1M count=100
          dd if=/dev/zero of=vos-efi.img bs=1M count=100

          echo "\nCheck Virtual Disks Images"
          ls -l vos-*.img

      - name: Setup Loop Devices and Run Integration Test
        run: |
          # Create loop devices
          LOOP_VAR=$(losetup -Pf --show vos-var.img)
          LOOP_A=$(losetup -Pf --show vos-a.img)
          LOOP_B=$(losetup -Pf --show vos-b.img)
          LOOP_BOOT=$(losetup -Pf --show vos-boot.img)
          LOOP_EFI=$(losetup -Pf --show vos-efi.img)

          # Wait for the system to update the block device information
          sleep 10

          # Format the loop devices
          mkfs.ext4 -L vos-var $LOOP_VAR
          mkfs.ext4 -L vos-a $LOOP_A
          mkfs.ext4 -L vos-b $LOOP_B
          mkfs.ext4 -L vos-boot $LOOP_BOOT
          mkfs.vfat -n vos-efi $LOOP_EFI

          # Add a delay to give the system time to update the block device information
          sleep 10

          # Check loop devices
          losetup -a
          lsblk -J -o "NAME,FSTYPE,LABEL,MOUNTPOINT,UUID"

          # Check if loop devices exist in the filesystem
          ls /dev/loop*

          # Run integration test
          ./abrootv2 status --verbose

      - name: Additional Debug Information
        run: |
          echo "Loop Devices:"
          losetup -a

          echo "Block Devices:"
          lsblk -a

          echo "Disk Information:"
          fdisk -l

          echo "Filesystem Types:"
          blkid

  release:
    name: Release
    needs: [test]
    runs-on: ubuntu-latest
    if: github.repository == 'vanilla-os/ABRoot' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "continuous"
          prerelease: true
          name: "Continuous Build"
          files: |
            abrootv2.tar.gz
            abroot-man.tar.gz
